---
title: "Practical2.part3"
output: html_document
date: "2023-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE, warning=FALSE}
source(here::here("script/setup.R"))
```
a)
```{r}

# Load necessary libraries
library(readr)
library(dplyr)
library(lubridate)

# Read in the data
night_max <- read_csv("nightmax.csv")  # Replace "nightmax.csv" with the actual file name
night_min <- read_csv("nightmin.csv")

# Remove rows with missing values
night_max <- na.omit(night_max)
night_min <- na.omit(night_min)

# Convert 'Date' to a Date object
night_max$date <- as.Date(night_max$date)
night_min$date <- as.Date(night_min$date)

# Subset the data for summer months (June to September)
summer_night_max <- night_max[format(night_max$date,"%m") %in% c("06", "07", "08", "09"), ] 

# Subset the winter months
winter_night_min <- night_min[format(night_min$date, "%m") %in% c("11", "12", "01", "02"), ]



# Plot the original data
plot(summer_night_max$date, summer_night_max$night.max, type = "l", xlab = "Date", ylab = "Night Max Temperature", main = "Summer Night Max Temperatures")

plot(winter_night_min$date, winter_night_min$night.min, type = "l", xlab = "Date", ylab = "Night Min Temperature", main = "Winter Night Min Temperatures")

```

```{r}
install.packages("tseries")
library(tseries)

# Perform runs test for summer night maximum temperatures
runs_test_result_summer_max <- runs.test(summer_night_max$night.max)
cat("Runs Test Result for Summer Night Max Temperatures:\n")
print(runs_test_result_summer_max)

# Perform runs test for winter night minimum temperatures
runs_test_result_winter_min <- runs.test(winter_night_min$night.min)
cat("\nRuns Test Result for Winter Night Min Temperatures:\n")
print(runs_test_result_winter_min)

```


